-- CreateEnum
CREATE TYPE "HospitalSpeciality" AS ENUM ('SUPER_SPECIALTY', 'MULTI_SPECIALTY', 'FERTILITY', 'EYE_CARE', 'CARDIAC', 'NEPHROLOGY', 'CANCER_TREATMENT', 'GENERAL', 'CHILDRENS_SPECIALTY', 'MATERNITY', 'ORTHOPEDIC', 'NEUROLOGY', 'PSYCHIATRY', 'GERIATRIC', 'DERMATOLOGY', 'GASTROENTEROLOGY', 'PULMONOLOGY', 'RHEUMATOLOGY', 'UROLOGY', 'ENT', 'DENTAL', 'ALLERGY', 'ENDOCRINOLOGY', 'PLASTIC_SURGERY', 'REHABILITATION_CENTER');

-- AlterTable
ALTER TABLE "hospitals" ADD COLUMN     "speciality" "HospitalSpeciality" NOT NULL DEFAULT 'GENERAL';
