/*
  Warnings:

  - The `specialization` column on the `doctors` table would be dropped and recreated. This will lead to data loss if there is data in the column.

*/
-- CreateEnum
CREATE TYPE "DoctorSpecialization" AS ENUM ('GENERAL_PRACTITIONER', 'ANESTHESIOLOGIST', 'CARDIOLOGIST', 'DERMATOLOGIST', 'EMERGENCY_MEDICINE_PHYSICIAN', 'ENDOCRINOLOGIST', 'FAMILY_MEDICINE_PHYSICIAN', 'GASTROENTEROLOGIST', 'GERIATRICIAN', 'HEMATOLOGIST', 'INFECTIOUS_DISEASE_SPECIALIST', 'INTERNIST', 'NEONATOLOGIST', 'NEPHROLOGIST', 'NEUROLOGIST', 'OBSTETRICIAN_GYNECOLOGIST', 'ONCOLOGIST', 'OPHTHALMOLOGIST', 'ORTHOPEDIC_SURGEON', 'OTOLARYNGOLOGIST', 'PEDIATRICIAN', 'PHYSICAL_MEDICINE_REHABILITATION_PHYSICIAN', 'PLASTIC_SURGEON', 'PSYCHIATRIST', 'PULMONOLOGIST', 'RADIOLOGIST', 'RHEUMATOLOGIST', 'SURGEON', 'UROLOGIST', 'ALLERGIST_IMMUNOLOGIST', 'INFECTIOUS_DISEASE_PHYSICIAN');

-- AlterTable
ALTER TABLE "doctors" DROP COLUMN "specialization",
ADD COLUMN     "specialization" "DoctorSpecialization" NOT NULL DEFAULT 'GENERAL_PRACTITIONER';
